config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
  }

  resources :videos, only: [:new, :create] do 
    member do
      post :reaction
    end
  end

  match '*path', :to => 'application#redirect_to_root_path', via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/emotion.rb
class Emotion < ActiveRecord::Base
  belongs_to :user
  belongs_to :video

  enum emotion_type: { like: 0, dislike: 1 }

  validates :user_id, uniqueness: { scope: :video_id }
end

app/models/form/share_video.rb
module Form
  class ShareVideo
    include ActiveModel::Model

    FORMAT_YOUTUBE_LINK = /\A((?:https?:)?\/\/)?((?:www|m)\.)?((?:youtube(-nocookie)?\.com|youtu.be))(\/(?:[\w\-]+\?v=|embed\/|v\/)?)([\w\-]+)(\S+)?\z/
    
    attr_accessor :url, :user_id
    
    validates :url, presence: true, format: { with: FORMAT_YOUTUBE_LINK }

    def share
      return false if invalid?

      video = VideoInfo.new url
      Video.create! embed_url: video.embed_url, description: video.description, title: video.title, user_id: user_id, url: url

      true
    rescue ActiveRecord::ActiveRecordError, VideoInfo::UrlError => e
      errors.add(:base, e.message)

      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :videos
  has_many :emotions

  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 6 }
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  has_many :emotions

  validates :url, presence: true, uniqueness: { case_sensitive: false }
  validates :title, presence: true
  validates :embed_url, presence: true

  scope :newest, -> { order(created_at: :desc) }
  scope :with_count_like, (lambda do
    select("videos.*, COUNT(emotions.id) as count_like")
      .joins("LEFT OUTER JOIN emotions ON emotions.video_id = videos.id AND emotions.emotion_type = 0")
      .group("videos.id")
  end)

  def count_dislike
    emotions.count - count_like
  end

  def like_voted_by? user_id
    emotion = emotions.find { |emo| emo.user_id == user_id && emo.emotion_type == "like"}

    emotion.present? ? "voted" : ""
  end

  def dislike_voted_by? user_id
    emotion = emotions.find { |emo| emo.user_id == user_id && emo.emotion_type == "dislike"} 

    emotion.present? ? "voted" : ""
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def redirect_to_root_path
    redirect_to root_path
  end

  def authenticate_user!
    unless user_signed_in?
      redirect_to_root_path
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user = User.new
    @videos = Video.includes(:user, :emotions).with_count_like.newest.page(params[:page]).per 5
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    @video = VideoInfo.new('https://www.youtube.com/watch?v=mr0gyhwXM4w')


    @title = @video.title
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    return signin_for_user if User.find_by email: sign_in_params[:email]
      
    signup_for_user
  end

  private

  def signin_for_user
    self.resource = warden.authenticate(auth_options)

    if resource
      sign_in(resource_name, resource)
      
      redirect_to root_path
    else
      @error = "Wrong password!"
      respond_to do |format|
        format.js
      end
    end
  end

  def signup_for_user
    user = User.new(sign_in_params)

    if user.save
      sign_in(:user, user)

      redirect_to root_path
    else
      @error = user.errors.full_messages.first
      respond_to do |format|
        format.js
      end
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :authenticate_user!

  def new
    @video = Form::ShareVideo.new
  end

  def create
    @video = Form::ShareVideo.new video_params

    if @video.share
      redirect_to root_path
    else
      render :new
    end
  end

  def reaction
    emotion = Emotion.find_by video_id: params[:id], user: current_user
    emotion_type = params[:emotion_type].to_i

    if emotion
      if emotion.read_attribute_before_type_cast(:emotion_type) == emotion_type
        destroy_emotion(emotion)
      else
        switch_emotion emotion
      end
    else
      Emotion.create! video_id: params[:id], user: current_user, emotion_type: emotion_type
    end

    @video = Video.with_count_like.find_by id: params[:id]

    respond_to do |format|
      format.js
    end
  end

  private

  def video_params
    params.require(:form_share_video).permit(:url).merge user_id: current_user.id
  end

  def check_current_user
    redirect_to root_path unless current_user
  end

  def switch_emotion emotion
    emotion.like? ? emotion.dislike! : emotion.like!
  end

  def destroy_emotion emotion
    emotion.destroy!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= paginate @videos, theme: "twitter-bootstrap-4",
                   pagination_class: "pagination-sm",
                   nav_class: "d-inline-b"
                   %>

<% @videos.map do |video| %>
  <div class="row">
    <div class="col-lg-12 col-xl-6">
      <iframe src="<%= video.embed_url %>"
         width="560" height="315" frameborder="0" allowfullscreen>
      </iframe>
    </div>

    <div class="col-lg-12 col-xl-6">
      <h4 class="title"><%= video.title %></h4>
      <p> Shared by <%= video.user.email %> </p>
      <p> Description: <%= video.description %> </p>
      <p> 
        <span class="count-like-<%= video.id %>"><%= video.count_like %></span>

        <span class="like-<%= video.id %>">
          <%= render "shared/emotions/like", video: video %>
        </span>

        &nbsp;
        <span class="count-dislike-<%= video.id %>"><%= video.count_dislike %></span>
        <span class="dislike-<%= video.id %>">
          <%= render "shared/emotions/dislike", video: video %>
        </span>
      </p>
    </div>
  </div>
<% end %>

<%= paginate @videos, theme: "twitter-bootstrap-4",
                   pagination_class: "pagination-sm",
                   nav_class: "d-inline-b"
                   %>

app/views/layouts/_header.html.erb
<header class="row">
  <div class="col-lg-12 col-xl-4 logo">
    <span class="fa fa-home fa-2xl lh-40"></span>
    &nbsp;
    <%=link_to "<h1>FUNNIES MOVIES</h1>".html_safe, root_path %>
  </div>

  <div class="col-lg-12 col-xl-8">
    <div class="right-nav">
      <% if current_user %>
        Welcome <%= current_user.email %>
        &nbsp;
        <%= link_to "Share A Movie", new_video_path, class: "btn btn-dark" %>
        &nbsp;
        <%= link_to "Logout", destroy_user_session_path, class: "btn btn-dark", method: :delete %>
      <% else %>
        <%= form_for(@user, url: user_session_path, remote: true, html: { id: :user_signin } ) do |f| %>
          <%= f.email_field :email, autofocus: true, id: :user_signin_email, placeholder: "Email" %>

          <%= f.password_field :password, id: :user_signin_password, placeholder: "Password" %>
          <%= f.submit "Login/Register", class: "btn btn-dark" %>
        <% end %>
      <% end %>
    </div>
    <div id="error-message-session"></div>
  </div>

  <hr />
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SharedYoutube</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= render "layouts/header" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/emotions/_dislike.html.erb
<%= link_to "<span class='fa fa-thumbs-down #{ video.dislike_voted_by?(current_user.id) if current_user }'></span>".html_safe, reaction_video_path(video, emotion_type: 1), method: :post, remote: true %>

app/views/shared/emotions/_like.html.erb
<%= link_to "<span class='fa fa-thumbs-up #{ video.like_voted_by?(current_user.id) if current_user }'></span>".html_safe, reaction_video_path(video, emotion_type: 0), method: :post, remote: true %>

app/views/videos/create.js.erb
$("#error-message-share").html("<%= j render('shared/error_messages', resource: @video) %>");

app/views/videos/new.html.erb
<div class="card">
  <h4>Share A Youtube Movie </h4>
  <%= render "shared/error_messages", resource: @video %>

  <%= form_for(@video, url: videos_url) do |f| %>
    <%= f.text_field :url, placeholder: "Enter Your Link", class: "form-control" %>
    <%= f.submit "Share", class: "btn btn-dark button-share" %>
  <% end %>
</div>

app/views/videos/reaction.js.erb
$('.count-like-<%= @video.id %>').html('<%= @video.count_like %>');
$('.count-dislike-<%= @video.id %>').html('<%= @video.count_dislike %>');
$('.like-<%= @video.id %>').html('<%= j render("shared/emotions/like", video: @video) %>');
$('.dislike-<%= @video.id %>').html('<%= j render("shared/emotions/dislike", video: @video) %>');